### ISSUE TITLE
Close Button does not appear in infobox

### ISSUE THREAD

**Issue by rajat-odu** [Experity/Embedded-Map#3]
Hello,
          I tried everything but I did not get an idea on how to show the close button on hospital infobox. Need ideas on how to perform this in this DocuTAP embedded maps.

Thanks

**Comment by aschuster3** [comment]
Hey @rajat-odu,
We'll need some steps to reproduce your problem.  What have you tried?  Can you show us any errors that you're getting?

**Comment by rajat-odu** [comment]
Thanks for replying back so promptly. All I need is to display the close button on the info box on the google maps in DocuTAP embedded maps.

**Comment by aschuster3** [comment]
Could you post a screenshot of some sort?  Maybe what you have, with another one illustrating what you want?

**Comment by rajat-odu** [comment]
[screen shot.docx](https://github.com/DocuTAP/Embedded-Map/files/1863985/screen.shot.docx)


 I need to add the close sign on the info box

**Comment by aschuster3** [comment]
I think I found a solution for you.  We have a method named `resetWindow` that puts the infobox in the default state.  In order to use it, you must add it to the templates.  Here's a minimum code implementation by adding a `<span>` to the "map_full_hospital" template:
```html
  <script id="map_full_hospital" type="text/template">
    <!-- This is the important part -->
    <span onClick='resetWindow({{id}}, false)'>X</span>
    <!-- ^^^^^^^^^^^^^^^^^^^^^^^^^^ -->
    <div class="map-window-full" id="hospital-window-{{id}}">
      <h5 class="opensans"><strong>{{{hospital_name_link}}}</strong></h5>
      <h5 class="opensans"><strong class="current_wait_placeholder">{{{current_queue_length}}}</strong>&nbsp;in line.</h5>
      <h5 class="opensans">{{{address_1}}}</h5>
      <h5 class="opensans">{{{address_2}}}</h5>
      <h5 class="opensans">{{{city}}}, {{{state}}} {{{zip}}}</h5>
      <h5 class="opensans">{{{phone_number}}}</h5>{{{schedule_button}}}
    </div>
  </script>
```

The above will look like this:
![infobox close button](http://g.recordit.co/jq0dmzN8Cz.gif)

Hope that helps!

**Comment by databyte** [comment]
And you can style that `x` to the right or make it pretty in other ways.

**Comment by rajat-odu** [comment]
Thanks for the help. I will try it and let you know.

**Comment by rajat-odu** [comment]
aschuster3 Thanks. It worked !!!
